echo "$MYSQL_MAIN_DATABASE"
mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e \
  "CREATE DATABASE IF NOT EXISTS $MYSQL_MAIN_DATABASE;
   GRANT ALL ON $MYSQL_MAIN_DATABASE.* TO $MYSQL_USER@'%' IDENTIFIED BY '$MYSQL_PASSWORD'"

echo "$MYSQL_TEST_DATABASE"
mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e \
  "CREATE DATABASE IF NOT EXISTS $MYSQL_TEST_DATABASE;
   GRANT ALL ON $MYSQL_TEST_DATABASE.* TO $MYSQL_USER@'%' IDENTIFIED BY '$MYSQL_PASSWORD'"
